boostcampwm2023/iOS08-WeTri

iOS/.gitignore
iOS/.swiftformat
iOS/.swiftlint.yml
iOS/Plugins/IOS/Package.swift
iOS/Plugins/IOS/Plugin.swift
iOS/Plugins/IOS/ProjectDescriptionHelpers/LocalHelper.swift
iOS/Plugins/IOS/Sources/tuist-my-cli/main.swift
iOS/Projects/App/Project.swift
iOS/Projects/App/Resources/LaunchScreen.storyboard
iOS/Projects/App/Sources/AppDelegate.swift
iOS/Projects/App/Sources/SceneDelegate.swift
iOS/Projects/App/Sources/ViewController.swift
iOS/Tuist/Config.swift
iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
iOS/Tuist/ProjectDescriptionHelpers/Scripts+Templates.swift
iOS/Workspace.swift

|Tuist Apply|
|:-:|
|![TuistApply](https://github.com/JongPyoAhn/Python/assets/68585628/cb530ba5-e2ba-42d0-b681-3e952075d4ff)|
<br/><br/>
- Xcode 에서 빈번하게 발생하는 Confilict를 피하고자 [Tuist적용](https://docs.tuist.io/tutorial/get-started)
- swiftLint와 Swift-format을 활용하여 컨벤션 강화  
- Airbnb 컨벤션 활용
- Airbnb의 Formatter 적용 문제 발생
- 일반적인 `.swiftformat`의 형식이 다름
- SPM을 통해 적용하려고 했지만, `Package`만 적용되고 `AppTarget`은 적용되지 않았음
- 따라서 글월 팀의 독자적인 swiftformat 사용
- 가장 최 상단에 존재하는 App에서 Project.swift를 생성
<br/><br/>
- https://baegteun.tistory.com/2
- https://okanghoon.medium.com/xcode-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EA%B4%80%EB%A6%AC%EB%A5%BC-%EC%9C%84%ED%95%9C-tuist-%EC%95%8C%EC%95%84%EB%B3%B4%EA%B8%B0-6a92950780be
<br/><br/>
---
- Closed: #1

[GWL-3] Tuist 프로젝트 세팅

---

iOS/Projects/App/Project.swift
iOS/Projects/Core/Network/Project.swift
iOS/Projects/Core/Network/Sources/MockURLSession.swift
iOS/Projects/Core/Network/Sources/TNEndPoint.swift
iOS/Projects/Core/Network/Sources/TNError.swift
iOS/Projects/Core/Network/Sources/TNHeader.swift
iOS/Projects/Core/Network/Sources/TNHeaders.swift
iOS/Projects/Core/Network/Sources/TNMethod.swift
iOS/Projects/Core/Network/Sources/TNProvidable.swift
iOS/Projects/Core/Network/Sources/Trinet.swift
iOS/Projects/Core/Network/Sources/URLSessionProtocol.swift
iOS/Projects/Core/Network/Tests/Test.swift
iOS/Tuist/ProjectDescriptionHelpers/TargetDependency.swift

|Trinet Coverage 91%|
|:-:|
|<img width="1426" alt="image" src="https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/e31f9fbd-8843-4a03-91d7-c1ec9968b404">|
<br/><br/>
- 서버와 서로 API 구조를 논의하지 않았으므로 협의 필요
- URLSessionProtocol 생성
- async 와 관련된 Mock
- Completion과 관련된 Mock
- 기존 Provider쪽에 있던 endpoint의 request를 endpoint 파일로 옮김
<br/><br/>
1. <a id="ref1">[[Swift] Mock 을 이용한 Network Unit Test 하기](https://sujinnaljin.medium.com/swift-mock-을-이용한-network-unit-test-하기-a69570defb41)</a>
2. [Moya/Moya: Network abstraction layer written in Swift](https://github.com/Moya/Moya)
<br/><br/>
---
- Closed: #30

[GWL-7] Network 라이브러리 구현

---

iOS/Projects/Features/Record/Project.swift
iOS/Projects/Shared/TNCocoaCombine/Project.swift
iOS/Projects/Shared/TNCocoaCombine/Sources/EventSubscription.swift
iOS/Projects/Shared/TNCocoaCombine/Sources/UIControl+Publisher.swift
iOS/Tuist/ProjectDescriptionHelpers/TargetDependency.swift

- UIControl의 객체를 Event를 Publisher하는 객체로 어떻게 만들까에 대한 고민 (combine을 활용한)
- [TNCombineCocoa를 직접 구현](https://www.notion.so/geul-woll/TNCocoaCombine-4d8dd06e1690442eae57d6bcfe6ce0db?d=23eb62c1fcda4feb90c1a1325f80b238#559890e01bd94ea8a29d06c13554482b)
- UIView에 적용 가능한 UITapGesture또한 확장 가능
- 작성한 코드를 어떤 식으로 테스트 할지 결정
- 현재는 테스트코드 작성 불가
<br/><br/>
<br/><br/>
---
- Closed: #40

[GWL-41] TNCombineCococa 구현 

---

iOS/Projects/Shared/DesignSystem/Sources/GWPageConrol.swift
iOS/Projects/Shared/DesignSystem/Sources/GWRoundShadowView.swift
iOS/Projects/Shared/DesignSystem/Sources/GWShadow.swift

|GWPgaeControl|
|:-:|
|![image](https://github.com/boostcampwm2023/iOS08-WeTri/assets/103064352/16db80b0-0676-4034-9785-0f1bf73d55b8)|
<br/><br/>
- pageControl 구현을 위해 autolayout 사용
- Width를 동적으로 변환할 수 있게 pageNSConstraints를 담아 해결했습니다.
<br/><br/>
- https://www.swiftbysundell.com/articles/rounded-corners-uikit-swiftui/
<br/><br/>
---
- Closed: #53

[GWL-51] Design System Page Control 생성

---

iOS/.swiftformat
iOS/.swiftlint.yml
iOS/Makefile
iOS/Projects/Shared/TNCocoaCombine/Project.swift
iOS/Tuist/ProjectDescriptionHelpers/Scripts+Templates.swift

|Name|
|:-:|
|<img src="https://github.com/JongPyoAhn/Python/assets/68585628/d71e86ac-1f5b-4efd-8ec7-c353691d0afa">|
<br/><br/>
없음
<br/><br/>
- [swiftLint 공식문서](https://realm.github.io/SwiftLint/line_length.html)
<br/><br/>
---
- Closed: #60

[GWL-53] SwiftLint 수정

---

.github/workflows/iOS_CI.yml
iOS/Projects/Features/Record/Tests/RecordFeatureTests.swift

|테스트해온 과정|터미널로 동작시킨 make test|
|:-:|:-:|
|<img width="861" alt="image" src="https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/4f23a99f-7bf2-4b0b-a6cb-b5293423815a">|![Screen Recording 2023-11-18 at 6 34 54 PM](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/43eb3e94-2776-4fe0-82fe-7bdd6a0c806a)|
<br/><br/>
Pull Request를 올릴 때 리뷰어끼리 코드를 파악하고 리뷰를 다는 방식으로 merge를 진행해왔지만, 가끔씩 파일을 다른 폴더에 두었다든지, 알고보니 에러가 내제된 코드였다든지, 그 밖의 여러 상황에 의해 다시 수정작업한 PR을 올리고는 합니다.
저희는 이러한 리소스를 사전에 방지하고자 테스트 코드를 만들고 수행하여 정상적인 코드인지를 판단하는 작업을 진행했습니다. 하지만, 이것 역시 Xcode 내에서 리뷰어마다 일일히 테스트코드를 동작시킬 수는 없는 노릇입니다.
그래서 GIthub Action을 이용해서 Pull Request가 올라올 때마다 test code를 자동으로 실행시켜주는 플로우를 만들기로 결심했습니다.
`Xcode 15.0.1`을 쓰고 있는 저희 프로젝트에서는 Resource(e.g. Assets)에 등록되어있는 색상을 자동으로 Xcode가 생성해주지만, `macos-latest` 의 최대 버전은 …

[GWL-54] Tuist Test Github Action 적용

---

iOS/Projects/App/WeTri/Project.swift
iOS/Projects/Features/Record/Project.swift
iOS/Projects/Features/Record/Sources/Presentation/Common/Coordinator/WorkoutCoordinator.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/RouteMapScene/WorkoutRouteMapViewController.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/RouteMapScene/WorkoutRouteMapViewModel.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/SessionScene/SessionParticipantCell.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/SessionScene/WorkoutSessionViewController.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/SessionScene/WorkoutSessionViewModel.swift
iOS/Tuist/ProjectDescriptionHelpers/Target+Templates.swift

|Name|
|:-:|
|<img src="https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/5938bda0-afba-47f0-b0d9-8760f2dba594" width="33%"/>|
<br/><br/>
운동 세션에서 두 번째 화면에서 지도를 보여주는 UI를 구현했습니다.
아직은 위치가 이동될 때마다 그려지는 방식으로 구현했습니다., 백그라운드 진입 로직은 추후 구현할 예정입니다.
- WorkoutSummaryViewController쪽의 네이밍을 수정했습니다.
- WorkoutSummary -> WorkoutSession
- ParticipantsCollectionViewCell -> SessionParticipantCell
- 각 Target에 별도로 Info.plist를 넣어주어야 하는 경우가 있는데, 기본값으로 넘겨주는 값을 덮어씌우다보니 문제가 발생하게 되었습니다. 그래서 각 Target 메서드마다 갖고있어야 하는 Info.plist 코드는 메서드 내부로 옮기고, 추가로 덧붙일 Info.Plist를 외부에서 받아 처리하도록 수정했습니다.
<br/><br/>
1. [MapPolyline | Apple Developer Documentation](https://developer.apple.com/documentation/mapkit/mappolyline)
2. [What's New in MapKit | WWDC2015](https://developer.apple.com/wwdc15/206?time=1376)
<br/><br/>
---
- …

[GWL-25] 지도 화면 UI 구현

---

iOS/Projects/Shared/CombineCocoa/Project.swift
iOS/Projects/Shared/CombineCocoa/Sources/Publisher+bind.swift
iOS/Projects/Shared/CombineCocoa/Tests/Publisher+bindTests.swift

단순히 subject send하는 과정을 sink 클로저로 처리하는 것이 이쁘지 않아보였고, RxSwift 메서드에 착안하여 `bind(to:)`를 만들게 되었습니다.<sup>[[1]](#ref1)</sup>
```swift
let subject: PassthroughSubject<Void, Never> = .init()
// 전
button.publisher(.touchUpInside)
.sink { _ in
subject.send(())
}
.store(in: &subscriptions)
// 후
button.publisher(.touchUpInside)
.map { _ in Void() }
.bind(to: subject)
.store(in: &subscriptions)
```
<br/><br/>
1. <a id="ref1">[Observable Bind.swift L19-L24](https://github.com/ReactiveX/RxSwift/blob/65bec4c253418c46ddc136424f46f333f086be1a/RxCocoa/Common/Observable%2BBind.swift#L19-L24)</a>
<br/><br/>
---
- Closed: #102

[GWL-74] CocoaCombine bind(to:) 추가

---

.github/workflows/iOS_CI.yml
iOS/Projects/Features/Record/Sources/Domain/UseCases/Protocol/RecordUpdateUseCaseRepresentable.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/RouteMapScene/WorkoutRouteMapViewController.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/RouteMapScene/WorkoutRouteMapViewModel.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/SessionScene/WorkoutSessionViewController.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/SessionScene/WorkoutSessionViewModel.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/WorkoutSessionContainerViewController.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/WorkoutSessionContainerViewModel.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSummaryScene/WorkoutSummaryViewController.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSummaryScene/WorkoutSummaryViewModel.swift
iOS/Projects/Shared/Log/Sources/Logger.swift

|UI|
|:-:|
|<img src="https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/55e5a167-eba8-4c86-ba2f-e908bb61b8ac" width="50%"/>|
|View Hierarchy|
|![](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/c2a412f8-3e75-4d28-87e5-e12fa339f0c5)|
<br/><br/>
- 지도 뷰(Route Map)와 운동 세션(Workout Session)을 하나의 PageController로 설정
- GWPageControl를 설정했는데 원하는대로 뷰가 설정되지 않았음
- @MaraMincho님과 상의 후 수정 예정
- Swiftformat이 적용되지 않은 상태이면 CI 실패가 뜨도록 설정
<br/><br/>
- 없음
---
- #112

[GWL-84] Workout Session 전체 뷰 구성 + Swiftformat CI 추가

---

iOS/Projects/Shared/DesignSystem/Sources/GWPageConrol.swift

|GWPageControl|
|:-:|
|![image](https://github.com/boostcampwm2023/iOS08-WeTri/assets/103064352/e2b18cb4-364d-4e28-804c-070d5f891142)|
<br/><br/>
- UILabel이 스스로 크기를 갖을 수 있는 이유는 intrinsicContentSize 때문
- 실제 CustomView에서도 intrinsicConstSize를 override하여 ContentSize를 갖게 함
- 이를 통해 언급했던 버그 수정
-  https://github.com/boostcampwm2023/iOS08-WeTri/pull/117
<br/>
언제 intrinsicContentSize가 호출되는지 확인
<br/>
<br/><br/>
https://medium.com/@vialyx/import-uikit-what-is-intrinsic-content-size-20ae302f21f3
<br/><br/>
---
- Closed: #125

[GWL-125] GWPageController 스스로가 Size를 갖을 수 있도록 코드 변경

---

iOS/Projects/Shared/CombineCocoa/Sources/EventSubscription.swift
iOS/Projects/Shared/CombineCocoa/Sources/Publisher+withLatestFrom.swift
iOS/Projects/Shared/CombineCocoa/Tests/Publisher+WithLatestFromTests.swift
iOS/Projects/Shared/CombineCocoa/Tests/UIControl+PublisherTests.swift

|Code Coverage 100%|
|:-:|
|![image](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/4f941fae-5305-4262-a1fc-03eba70f795c)|
<br/><br/>
- #130 에서 WithLatestFrom이 필요해서 추가하였습니다.
- 그리고 미비된 테스트 코드를 추가해서 CombineCocoa 한정 Code coverage 100% 달성했습니다. 🎉🎉
- `@objc`는 테스트하기가 어려워서 UIAction으로 변경했어요. addTarget 대신에 addAction을 써서요!
<br/><br/>
1. [Combine+WithLatestFrom.swift](https://gist.github.com/freak4pc/8d46ea6a6f5e5902c3fb5eba440a55c3)
<br/><br/>
---
- Closed: #37

[GWL-37] CocoaCombine withLatestFrom 추가 + Code Coverage 100%

---

BackEnd/src/live-workouts/events/events.gateway.ts
BackEnd/src/live-workouts/events/events.module.ts
BackEnd/src/live-workouts/events/types/custom-websocket.type.ts

|웹 소켓 검증 로직 구현|
|:-:|
|![image](https://github.com/boostcampwm2023/iOS08-WeTri/assets/56383948/9e64cec1-f715-4f64-87fe-b6b8ee021036)|
|![image](https://github.com/boostcampwm2023/iOS08-WeTri/assets/56383948/2d18765f-ae40-4be9-8694-c9b7f86c2aa5)|
<br/><br/>
<br/>
- 처음에는 UseGuard를 이용해서 WebsocketGuard를 구현하려고 했습니다. 하지만, 소켓이 연결된 후에 클라이언트가 메시지를 보내기 전까지 작동하지 않음을 보았습니다.
- handdleConnection이 Ws으로 연결전 HTTP를 통해 업그레이드 헤더를 보내는 것을 확인했습니다.
- 이후 handdleConnection위에 UseGuard를 달았지만, 작동하지 않았고, nest 공식 github에도 그와 관련된 게시물을 보았습니다.
- 방법은 시작할 때 미들웨어를 두고 검증하는 것입니다.
- 하지만, 직접 미들웨어를 만들어서 하기에는 남아있는 기능도 많았고, WebSocket과 SocketIO의 차이점으로인해 뒤로 미뤘습니다.
- 검증하는 로직을 메서드로 작성해서 handdleconnection에 추가했습니다.
- 그 외에 UseGuard를 이용하면 WebSocket 통신 중간에도, 토큰을 이용한 검증이 가능합니다.
<br/>
<br/>
- [this guard is not …

[GWL-151] 웹소캣 AuthGuard 구현 -> 검증 verify 메서드 구현

---

BackEnd/src/app.module.ts
BackEnd/src/common/redis.module.ts
BackEnd/src/config/redis.config.ts
BackEnd/src/live-workouts/events/events.gateway.ts
BackEnd/src/live-workouts/events/events.module.ts
BackEnd/src/live-workouts/events/extensionWebSocket.service.ts
BackEnd/src/live-workouts/events/extensions/extensionWebSocket.ts
BackEnd/src/live-workouts/events/extensions/extensionWebSocketServer.ts
BackEnd/src/live-workouts/events/types/custom-websocket.type.ts
BackEnd/src/live-workouts/matches/matches.module.ts
BackEnd/src/live-workouts/matches/matches.service.spec.ts
BackEnd/src/live-workouts/matches/matches.service.ts

client.id는 유저의 publicId를 뜻합니다. 
client: WeTriWebSocket -> WebSocket을 확장한 custom socket
기존에는 room을 서버내에서만 저장하고 있었습니다. 
이렇게 하면 문제점은 여러 서버간의 존재하는 room에 브로드캐스트(room에 있는 모든 유저에게 메시지 전송)를 하지 못합니다.
그래서 이 부분을 redis DB, redis pub/sub을 이용해서 구현했습니다.
이런 구조라고 생각하시면 됩니다.
그래서 전체적인 흐름을 말씀드리면 소켓에 연결할 때는 매칭 후이기 때문에 자신이 들어갈 roomId를 알고 있습니다. 
이 roomId를 전달해주면 서버에서는 `client.join(roomId);` 코드를 실행합니다. 
이 코드는 서버내 `rooms: Map<string, Set<string>>`에 key에 roomId를 value에 publicId를 저장합니다.
그리고 redis room에도 똑같은 구조로 저장해줍니다. 여기서 현재 서버내 roomId에 해당하는 방에 자신이 처음 들어갔다면 `room:roomId` 채널을 구독합니다. 이후 해당 채널에 메시지가 발행되면 channel에 roomId를 가져와서 그 방에 user에게 send 하는 용도로 사용됩니다.
`client.leave(roomId);` 이 코드는 roomId에 해당하는 room을 나갑니다. 서버내 룸도 나가고, redis 룸도 나갑니다. 
그리고 방에 자신이 마지막으로 나갔다면 `room:roomId` 채널을 구독 취소 해줍니다. 그러면 더 이상 해당 채널에서 발행되는 메시지는 받지 …

[GWL-158] redis 연결, redis 룸에 참가, 떠나기 ,redis pub/sub을 이용해서 브로드캐스트

---

iOS/Projects/Core/Keychain/Sources/Keychain.swift

❌
<br/><br/>
- 변경 이유
- 여러군데에서 사용할 것이라고 판단했습니다. 그래서, 인스턴스를 여러개 생성 할 필요도 없는 로직이기 때문에 인스턴스를 계속해서 생성하면서 비용을 높이는것 보다는 하나의 인스턴스만으로 사용하는게 옳다고 판단했습니다. 의존성을 주입해줄 때, 싱글톤으로 주입해주시면 될 것 같습니다.
<br/><br/>
❌
<br/><br/>
---
- Closed: #164

[GWL-164] Keychain 싱글톤 변경

---

BackEnd/src/workouts/dto/workout-response.dto.ts
BackEnd/src/workouts/entities/workout.entity.ts
BackEnd/src/workouts/workouts.service.spec.ts

|Workouts|
|:-:|
|![image](https://github.com/boostcampwm2023/iOS08-WeTri/assets/56383948/34a162e6-726c-4a93-a2ed-9c4d328a33e3)|
<br/>
<br/>
<br/>
- 다함님과의 소통으로 API의 마무리 도장을 쾅 찍었습니다.
- icon 스트링을 추가하고, 노션에 API를 작성했습니다!
<br/>
<br/><br/>
---
- Closed: #166

[GWL-166] Workouts API에 icon 이미지 컬럼 추가, Swagger 수정

---

iOS/Projects/App/WeTri/Sources/AScene/ViewController/AViewController.swift
iOS/Projects/App/WeTri/Sources/Application/SceneDelegate.swift
iOS/Projects/App/WeTri/Sources/CScene/ViewController/CViewController.swift
iOS/Projects/Core/Network/Sources/MockWebSocketSession.swift
iOS/Projects/Core/Network/Sources/TNSocketProvider.swift
iOS/Projects/Core/Network/Sources/URLSessionWebSocketProtocol.swift
iOS/Projects/Core/Network/Sources/WebSocketTaskProtocol.swift
iOS/Projects/Core/Network/Tests/SessionWebSocketProtocolTests.swift
iOS/Tuist/ProjectDescriptionHelpers/Target+Templates.swift

> [!Note]
>
> 해당 브랜치에서 세 번째 탭에 테스트 코드를 넣어두었습니다. 제 브랜치로 이동하시면 바로 소켓 테스트를 하실 수 있습니다!
|iPhone과 postman 간 소켓 통신 테스트|
|:-:|
|![Screen Recording 2023-11-29 at 9 23 28 PM](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/b6a4158b-357d-4bb8-b31c-24bf49534d3c)|
|생각한 구조|
|![image](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/ddb9be6c-cf92-45f2-89d0-a5079abe87a6)|
<br/><br/>
같이하기일 경우 다른 사람들의 데이터를 소켓으로 받아와서 업데이트를 해주어야했고, 혼자하기인 경우에는 소켓통신의 필요 없이 스스로 UI를 업데이트해주어야합니다. 이 분기처리를 어떻게 할지 고민한 결과, URLSession에서 사용되는 SocketTask를 protocol로 추상화하기로 결정했습니다.
지난 번에 논의했던 구조를 일부 가져왔습니다. 레포지토리에서 `혼자하기`인 경우 자체적으로 데이터를 리턴하고, `함께하기`인 경우 데이터로 전달하는 과정을 갖고 있는데요.
Repository에서 운동 모드를 인지하고 직접 나누는 행위에 대해 고민을 해보게 되었어요.
어찌보면 Repository에서 분기가 일어나는 로직이다보니, 흐름에 문제가 생겼을 때 빠르게 확인할 수 있지는 않을 것 같다는 결론을 내리게 …

[GWL-162] Trinet 소켓 Providable 추가 + 테스트 코드 추가

---

BackEnd/src/live-workouts/matches/dto/random-match.dto.ts
BackEnd/src/live-workouts/matches/matches.service.spec.ts
BackEnd/src/live-workouts/matches/matches.service.ts

|Matches|
|:-:|
|![image](https://github.com/boostcampwm2023/iOS08-WeTri/assets/56383948/5c0f64eb-0daf-4b0d-abaa-d222ed0330f3)|
<br/>
<br/>
<br/>
- Matches API가 노션에 등록 되었습니다.
<br/>
<br/><br/>
---
- Closed: #174

[GWL-174] Matches API nickname -> publicId로 수정

---

BackEnd/public/index.html
BackEnd/src/auth/auth.service.ts
BackEnd/src/auth/dto/signup.dto.ts
BackEnd/src/auth/guard/bearerToken.guard.ts
BackEnd/src/images/images.module.ts
BackEnd/src/posts/entities/posts.entity.ts
BackEnd/src/profiles/dto/create-profile.dto.ts
BackEnd/src/profiles/dto/update-profile.dto.ts
BackEnd/src/profiles/entities/profiles.entity.ts
BackEnd/src/profiles/exception/profile.exception.ts
BackEnd/src/profiles/profiles.controller.ts
BackEnd/src/profiles/profiles.module.ts
BackEnd/src/profiles/profiles.service.ts
BackEnd/src/users/users.service.ts

|Profile API 구현|
|:-:|
|![image](https://github.com/boostcampwm2023/iOS08-WeTri/assets/56383948/40b2dae9-8d8d-457e-80f5-4b4095a446a3)|
|![image](https://github.com/boostcampwm2023/iOS08-WeTri/assets/56383948/075480c0-8211-490b-a982-6db750a56d47)|
<br/>
<br/>
<br/>
- Profile에서 Get을 할 때, 최신 게시물의 9개까지 요청을 보내고, 이미지 URL과 게시물의 id를 리턴하도록 만들었습니다.
- Create 부분은 User 레포지토리에 로직이 존재하기에 삭제했습니다.
<br/>
<br/><br/>
---
- Closed: #176

[GWL-176] Profile API를 구현한다.

---

iOS/Projects/Core/Network/Sources/MockWebSocketSession.swift
iOS/Projects/Core/Network/Tests/SessionWebSocketProtocolTests.swift
iOS/Projects/Features/Record/Sources/Domain/Entities/WorkoutRealTimeModel.swift
iOS/Projects/Features/Record/Sources/Presentation/Common/Coordinator/WorkoutSessionCoordinator.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/SessionScene/SessionParticipantCell.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/SessionScene/WorkoutSessionViewController.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/WorkoutSessionContainerViewController.swift

|혼자하기 테스트|
|:-:|
|![RPReplay_Final1701502778](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/05e1d8d2-5216-46d3-9094-8ec5fd7586ce)|
<br/><br/>
MockWebSocketSession과 실서버와 동작을 동일하게 유지하기 위해서 테스트 코드를 실서버에서 오는 것과 동일하게 수정했고, 실패한 테스트를 성공시키기 위해 Session을 고쳐나갔습니다.
`MockWebSocketTask`와 `URLSessionWebSocketTask`는 `URLSessionWebSocketTask.Message`를 보내거나(send) 받게(receive)되는 코드를 담고 있습니다. 이 때 `MockWebSocketTask`는 Message타입이 `data(_:)`타입이거나 `string(_:)`타입이면 그 타입을 그대로 `receive`에 넘기도록 구현해두었으나, 실서버에서는 `data(_:)`로 보냈을 때 `string(_:)`타입으로 들어오게됩니다.
그리고 `WebSocketFrame<T>`타입으로 전달하면, receive메서드로 받았을 때 `WebSocketFrame`이 벗겨진 **`T`** 타입이 들어오게 됩니다.
실제 코드에서는 TNSocketProvider에서 `WebSocketFrame`에 담을 모델을 encode하여 session에게 Data타입으로 요청을 보냅니다. MockSession은 MockWebSocketTask에게 이벤트를 전달하고, MockWebSocketTask는 …

[GWL-85] 서버 구조에 맞게 웹 소켓 연동

---

iOS/Projects/App/WeTri/Sources/Application/SceneDelegate.swift
iOS/Projects/Features/SignUp/Sources/View/DatePickerBoxView.swift
iOS/Projects/Features/SignUp/Sources/View/NickNameBoxView.swift
iOS/Projects/Features/SignUp/Sources/View/NickNameCheckerView.swift
iOS/Projects/Features/SignUp/Sources/ViewController/SignUpContainerViewController.swift
iOS/Projects/Features/SignUp/Sources/ViewController/SignUpGenderBirthViewController.swift
iOS/Projects/Features/SignUp/Sources/ViewController/SignUpProfileViewController.swift

|결과 화면|
|:-:|
|<img src = "https://github.com/JongPyoAhn/Python/assets/68585628/89cf40c8-9e55-4547-9baf-f9fc4ff6a845" width="300" height="500">|
<br/><br/>
- 뷰를 어떻게 나눌지? 틀렸을 때 색상을 어떻게 설정할지? 에 대해 고민하였습니다.
- 뷰를 나누는 방법은 간단하게 색상이 같이 변경되거나 하나의 아이템(?)과 같은 단위로 사용할 수 있을 경우 뷰로 나누었습니다.
- 색상은 각 뷰의 역할대로 뷰 내부에서 처리할 수 있는 함수들을 선언하여 비즈니스로직과 합쳤을 때 바로 색상을 변경할 수 있게 하였습니다.
<br/><br/>
❌
<br/><br/>
---
- Closed: #218

[GWL-218] 회원가입(2) UI 구성

---

iOS/Projects/App/WeTri/Sources/Application/SceneDelegate.swift
iOS/Projects/Features/SignUp/Sources/ViewController/SignUpContainerViewController.swift
iOS/Projects/Features/SignUp/Sources/ViewController/SignUpGenderBirthViewController.swift
iOS/Projects/Features/SignUp/Sources/ViewController/SignUpProfileViewController.swift

|결과 화면|
|:-:|
|<img src = "https://github.com/JongPyoAhn/Python/assets/68585628/024176e7-b9e4-4939-86b6-2ea31eeea5bb" width="300" height="500">|
<br/><br/>
- PageControl로 이동할 때, 어떻게 이동해야할까?
- 팀원분들이 구현한 레퍼런스 2개를 볼 수 있었습니다.
저는 조금 다른 방식으로 구현했는데요.
내부에 navigationController를 넣을 필요 없이, 단 2개의 화면만 동작하기 때문에 `isHidden`을 활용해서 가볍게 처리해줬습니다.
ViewController가 분리되어있지 않다면, isHidden을 사용하게 될 경우 상당히 비대한 VC를 만들어 낼 것 입니다.
하지만, 현재처럼 ViewController가 분리되어있고 1:1로 각자의 ViewModel을 만들어줄 것이라면 VC의 비대는 일어나지 않을것이고 그렇기 때문에 navigationController가 아닌 isHidden을 선택했습니다.
<br/><br/>
❌
<br/><br/>
---
- Closed: #(issue-here)

[GWL-231] 회원가입 ContainerViewController 구현

---

iOS/Projects/Features/Profile/Project.swift
iOS/Projects/Features/Profile/Resources/Persistency/GetPosts.json
iOS/Projects/Features/Profile/Resources/Persistency/GetProfile.json
iOS/Projects/Features/Profile/Sources/Data/DTO/PostsRequestDTO.swift
iOS/Projects/Features/Profile/Sources/Data/DTO/PostsResponseDTO.swift
iOS/Projects/Features/Profile/Sources/Data/DTO/ProfileDTO.swift
iOS/Projects/Features/Profile/Sources/Data/Repositories/ProfileRepository.swift
iOS/Projects/Features/Profile/Sources/Domain/Interfaces/ProfileRepositoryRepresentable.swift
iOS/Projects/Features/Profile/Sources/Domain/UseCases/ProfileUseCase.swift
iOS/Projects/Features/Profile/Sources/Domain/UseCases/Protocol/ProfileUseCaseRepresentable.swift
iOS/Projects/Features/Profile/Sources/Presentation/ProfileScene/Coordinator/ProfileCoordinator.swift
iOS/Projects/Features/Profile/Sources/Presentation/ProfileScene/PostsEmptyStateView.swift
iOS/Projects/Features/Profile/Sources/Presentation/ProfileScene/ProfileLayouts/CompositionalLayoutSugarMethods.swift
iOS/Projects/Features/Profile/Sources/Presentation/ProfileScene/ProfileLayouts/SectionItem.swift
iOS/Projects/Features/Profile/Sources/Presentation/ProfileScene/ProfilePostCell.swift
iOS/Projects/Features/Profile/Sources/Presentation/ProfileScene/ProfileViewController.swift
iOS/Projects/Features/Profile/Sources/Presentation/ProfileScene/ProfileViewModel.swift

|데이터가 존재할 때|데이터가 존재하지 않을 때|
|:-:|:-:|
|![RPReplay_Final1701842494](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/7cfbca93-dac2-420b-ac57-8a6f137b7b07)|![RPReplay_Final1701761159](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/b1bbc15c-a85b-4bf9-ac23-d8e5c8ec57e1)|
<br/><br/>
ScrollViewDelegate로 현재 위치값을 기반으로 어느정도 밑으로 다다랐을 때 게시글을 요청하도록 구현했습니다(for 사용자 경험).
그러나, ScrollViewDelegate는 조금만 움직여도 빈번하게 호출되므로, 불필요한 Network요청을 제한하고자 특정 조건을 충족할 때만 데이터 요청을 갖도록 로직을 개선했습니다.
1. `ProfileUseCase`를 리팩토링했습니다.
요청으로 들어오는`nextRequestID`를 캐싱하면서 페이지네이션의 상태를 관리하였고, 덕분에 효율적인 데이터 로딩을 마련했습니다.
만약 처음으로 요청이 들어온 ID값이 있다면, 해당 ID값으로 요청이 들어간 이력이 있는지 확인하고, 없다면 Repository에게 데이터를 요청합니다. 만약 가져온 이력이 있다면 Empty를 리턴합니다(즉 무시합니다).
Profile 화면에서 Diffable DataSource의 Section은 아래 그림처럼 나뉩니다.
Cell이 하나라도 있다면 …

[GWL-201] Empty State View + 게시물 가져오기 Mock Data 테스트, 페이지네이션

---

BackEnd/src/live-workouts/events/events.gateway.ts
BackEnd/src/live-workouts/matches/dto/random-match.dto.ts
BackEnd/src/live-workouts/matches/matches.service.spec.ts
BackEnd/src/live-workouts/matches/matches.service.ts

<br/>
- 매칭 API의 자신을 표시하는 myPublicID 생성, events gateway 로깅
<br/>
<br/><br/>
---
- Closed: #280

[GWL-280] 매칭 API의 자신을 표시하는 myPublicID 생성, events gateway 로깅

---

BackEnd/src/common/common.service.spec.ts
BackEnd/src/common/common.service.ts
BackEnd/src/common/dto/base-paginate-res.dto.ts
BackEnd/src/common/mocks/mocks.ts
BackEnd/src/common/type/query-options.type.ts
BackEnd/src/images/images.controller.ts
BackEnd/src/images/intercepters/wetri-files.interceptor.ts
BackEnd/src/posts/queryOptions/get-create-update.queryOptions.ts

paginate 함수에서 발생할 수 있는 오류는 잘못 설정된 QueryBuilder에서 발생합니다.
여기서 join, select를 잘못 설정하면 sql 오류가 발생합니다.
이 오류는 서버와 관련된 오류이기 때문에 상세한 오류를 프론트로 보내줄 필요는 없고, internal server error를 발생하게 했습니다. (catch문에서)
대신 서버에서는 이 에러를 자세하게 알아야하기 때문에 try catch로 잡아서 Logger.error()로 error message 보여주도록 했습니다.
<br/><br/>
---
- Closed: #257

[GWL-257] common service 에러 처리, 테스트 코드 작성, 리팩토링

---

BackEnd/src/live-workouts/events/extensions/extensionWebSocketServer.ts
BackEnd/src/live-workouts/matches/constant/matches.constant.ts
BackEnd/src/live-workouts/matches/matches.service.ts

<br/>
- Json 직렬화 문제, 연결할 때, 소켓에 나머지 인원이 들어오지 못하는 문제
<br/>
<br/><br/>
---
- Closed: #282

[GWL-282] Json 직렬화 문제, 연결할 때, 소켓에 나머지 인원이 들어오지 못하는 문제

---

BackEnd/src/auth/auth.service.ts
BackEnd/src/live-workouts/events/events.gateway.ts
BackEnd/src/live-workouts/matches/matches.service.ts
BackEnd/src/records/entities/records.entity.ts

<br/>
- 토큰 에러 헨들링이 안되는 문제를 try catch로 잡고, client.close 해줬습니다. -> 따로 에러 메세지를 전송하려면 미들웨어를 두어야하는데, 이 경우 프로젝트가 끝난 이후에 하려고 합니다.
- gps 컬림을 longtext로 두어 최대 4기가 바이트까지 저장이 가능합니다.
- redis에서 값을 expired할 때, EX 600이 아닌 .expired메서드를 이용했습니다.
<br/>
<br/><br/>
---
- Closed: #290 
- Closed: #279

[Fix] 소켓 연결시 token에러 핸들링이 안되는 문제, record에 gps 컬럼이 255자였던 건 관하여

---

iOS/Makefile
iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift

배포 서버와 개발 서버가 분리되면서 저희 프로젝트에서도 개발과 릴리즈라는 두 갈래의 Configuration을 설정할 필요가 생겼습니다.
그래서 기존에 `Shared.xcconfig`에서 baseURL을 설정했던 것을 `Debug.xcconfig`, `Release.xcconfig`로 분리했습니다.
```
XCConfig
├── Server
│   ├── Debug.xcconfig
│   └── Release.xcconfig
└── Shared.xcconfig
```
release로 빌드하는 것과 debug로 빌드하는 것을 분리하기 위해 Scheme을 두 개씩 생성할까 고민했으나, Scheme의 개수가 n배로 증가하다보니 원하는 Scheme을 찾기 어렵다고 생각이 들었고, `Makefile`을 사용하여 release용 생성과 debug용 생성을 분리하는 게 낫다고 생각했습니다.
그래서 아래와 같이 만들었습니다.
- `make generate`: debug용으로 빌드합니다.
- `make release`: release용으로 빌드합니다.
항상 사용하는 `make generate`는 debug configuration을 가집니다. 하지만 실 배포 서버에서 테스트가 필요하다면 `make release`로 Xcode를 생성하기만 하면 됩니다.
1. [Adding a build configuration file to your project](https://developer.apple.com/documentation/xcode/adding-a-build-configuration-file-to-your-project) …

[GWL-295] 배포서버와 개발서버 분리

---

iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/WorkoutSessionContainerViewController.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/WorkoutSessionContainerViewModel.swift

|Page Control 애니메이션 움직이지 않았던 버그 수정|
|:-:|
|![RPReplay_Final1702110315](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/e322fad3-95d4-4e40-b445-d0275efddde5)|
<br/><br/>
운동 세션 화면에서 제대로 동작하지 않았던 버그를 수정했습니다.
1. 기록 API가 두 번 호출되는 버그를 고쳤습니다.
- 계속해서 새로운 구독이 생기게 되어 API 흐름이 여러번 호출되는 문제가 있었습니다. 하나의 흐름으로 처리해야 했기에 `share()` 오퍼레이터를 추가하여 해결했습니다.
2. pageControl이 동작하지 않았던 버그를 고쳤습니다.
- `PageViewControllerDataSource`에 넣어두었던 pageControl 이동 코드를 `PageViewControllerDelegate`로 이동해서 고쳤습니다.
---
- Closed: #300

[GWL-300] 운동 세션 화면 버그 수정

---

iOS/Projects/App/WeTri/Sources/Application/SceneDelegate.swift
iOS/Projects/Features/Login/Sources/Presentation/LoginScene/LoginViewController.swift

|iPhone 15 Pro|iPhone SE|
|:-:|:-:|
|<img src="https://github.com/JongPyoAhn/Python/assets/68585628/b312c199-bd45-471e-8d97-39f93f87ca07">|<img src="https://github.com/JongPyoAhn/Python/assets/68585628/2998e198-8d77-47d6-b72f-5a4ef81b4eaa">
|iPhone 15 Pro|iPhone SE|
|:-:|:-:|
|<img src="https://github.com/JongPyoAhn/Python/assets/68585628/45696605-e69a-4c0c-ab2a-4be773161e3c">|<img src="https://github.com/JongPyoAhn/Python/assets/68585628/30969eb7-a152-4ec5-bd4a-4a9ebd909681">
<br/><br/>
- 레이블에 링크를 어떻게 넣고 부분부분 파란색을 어떻게 칠하지..?
- NSMutableAttributedString을 사용하면 NSRange를 통해 원하는 하이퍼링크 색상(파란색)으로 문자의 범위를 색칠할 수 있다. 또한, textView를 사용해서 dataDetectorTypes를 link로 설정해주면 NSMutableAttributedString을 통해 링크로 설정한 글씨를 누르면 링크를 이동하도록 할 수 있다.
<br/><br/>
- [텍스트뷰의 텍스트 내 링크 하이퍼링크로 …

[GWL-303] 로고 추가된 로그인 화면 UI 작성

---

BackEnd/src/auth/auth.service.ts
BackEnd/src/profiles/dto/get-nickname-availability.dto.ts
BackEnd/src/profiles/profiles.controller.ts
BackEnd/src/profiles/profiles.service.ts

`api/v1/profiles/nickname-availability` Post 요청
- nickname 중복시 
```json
{
"code": 2010,
"errorMessage": "duplicated nickname error.",
"data": null
}
```
- 사용할 수 있는 nickname이라면
```json
{
"code": null,
"errorMessage": null,
"data": null
}
```
---
- Closed: #298

[GWL-298] 닉네임 중복 검사 api

---

iOS/Projects/App/WeTri/Sources/CommonScene/Coordinator/AppCoordinator.swift
iOS/Projects/Features/Record/Sources/Presentation/Common/Coordinator/WorkoutEnvironmentSetUpCoordinator.swift
iOS/Projects/Features/Record/Sources/Presentation/Common/Coordinator/WorkoutSessionCoordinator.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutEnvironmentScene/ViewController/WorkoutEnvironmentSetupViewController.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutEnvironmentScene/ViewController/WorkoutSelectViewController.swift

|Name|
|:-:|
|![Simulator Screen Recording - iPhone 15 Pro - 2023-12-10 at 11 49 28](https://github.com/boostcampwm2023/iOS08-WeTri/assets/103064352/d0a7a4ea-fca2-4eee-a50d-9052b56a1085)|
<br/><br/>
- PageViewController를 보면 내부에 `ScrollView`가 존재...
- 그래서 어떤 화면에서는 반드시 ScrollView의 isScrollEnabled을 건드려 줘야 했음.
- 문제 상황은 다음과 같음
- 첫번 째 화면에서 스크롤이 가능하면 안됨
- 두번 째 화면에서 스크롤이 가능해야 함
- 이대로 만들었는데 문제는, 첫번째 화면에서 스크롤 했을 때 다음 버튼을 연타하면 앱이 깨졌음
- 그래서 이유를 확인해 보니 Scroll애니메이션 도중에 isScrollEnabled가 true로 바뀌어 예상치 못한 흐름으로 흘러갔음.
- setViewControllers내부에, completionHandler를 처리하여 안전하게 처리
```swift 
func nextButtonDidTap() {
pageScrollView?.isScrollEnabled = false
gwPageControl.next()
pageViewController.setViewControllers([workoutPeerSelectViewController], direction: .forward, animated: true) { [weak self] _ in …
```

[Feat]: WorkoutEnvironmentViewController  popGestgure 버그 수정

---

iOS/Projects/App/WeTri/Sources/Application/AppDelegate.swift
iOS/Projects/App/WeTri/Sources/Application/SceneDelegate.swift
iOS/Projects/App/WeTri/Sources/CommonScene/Coordinator/AppCoordinator.swift
iOS/Projects/Features/SignUp/Sources/Presentation/SignUpProfileScene/SignUpProfileViewController.swift
iOS/Projects/Features/SignUp/Sources/Presentation/SignUpProfileScene/ViewModel/SignUpProfileViewModel.swift

❌
<br/><br/>
- 다운샘플링을 진행하면서 Input에 이미지 데이터를 전달하는 Subject를 실수로 지웠습니다.
<br/><br/>
❌
<br/><br/>
---
- Closed: #326

[GWL-326] 회원가입 완료버튼 활성화 안되는 현상 개선

---

iOS/Projects/App/WeTri/Sources/Application/SceneDelegate.swift
iOS/Projects/App/WeTri/Sources/CommonScene/Coordinator/AppCoordinator.swift
iOS/Projects/Core/Network/Sources/Mock/MockWebSocketSession.swift
iOS/Projects/Core/Network/Sources/Provider/TNSocketProvider.swift
iOS/Projects/Core/Network/Tests/SessionWebSocketProtocolTests.swift
iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutSocketRepository.swift
iOS/Projects/Features/Record/Sources/Domain/Entities/WorkoutRealTimeModel.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutEnvironmentScene/ViewModel/WorkoutEnvironmentSetupViewModel.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutPeerMatchingScene/ViewModel/WorkoutPeerRandomMatchingViewModel.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/SessionScene/WorkoutSessionViewController.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSummaryScene/WorkoutSummaryCardView.swift

|Name|
|:-:|
|![RPReplay_Final1702192397](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/01b8bff0-19de-436e-94b7-be7455c4cb91)|
<br/><br/>
- 혼자하기 시 소켓 모델이 달라 운동 데이터가 보이지 않는 버그 수정
- 요약 화면에서 단위를 보이지 않아 가독성이 떨어지는 현상 수정
- 세션에서 id가 아닌 nickname을 Diffable Datasource의 Item값으로 하여 뷰를 업데이트하도록 수정
---
- Closed: #308

[GWL-308] 운동 세션 중 소켓 버그와 디자인 일부 수정

---

iOS/Projects/Features/Record/Sources/Presentation/WorkoutSummaryScene/WorkoutSummaryCardView.swift

|전|후|
|:-:|:-:|
|![IMG_74525BC252A9-1](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/2967e398-8586-4672-be21-44f296d90ebf)|![IMG_4DE3254A07D2-1](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/b5da5216-bacc-42ea-b288-2d19ef0ee00e)|
<br/><br/>
운동 요약화면을 볼 때 운동했던 거리가 그려지는 것을 볼 수 있는데, 패딩값을 주는 게 보기 좋아보일 것 같아 이를 수정했습니다.
---
- Closed: #332

[GWL-332] 운동 요약 화면 중 경로 화면 확대되는 증상 수정

---

iOS/Projects/App/WeTri/Sources/CommonScene/Coordinator/AppCoordinator.swift
iOS/Projects/Features/SignUp/Project.swift
iOS/Projects/Features/SignUp/Sources/Domain/UseCase/SignUpUserDefaultsManagerUseCase.swift
iOS/Projects/Features/SignUp/Sources/Presentation/Common/Coordinator/SignUpFeatureCoordinator.swift
iOS/Projects/Shared/UserInformationManager/Sources/UserInformationManager.swift

N/A
<br/><br/>
N/A
<br/><br/>
N/A
<br/><br/>
---
- Closed: #312

[GWL-312] UserDefatuls를 통한 프로필 이미지 및, 닉네임 저장 하는 UseCase연결

---

iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/RouteMapScene/WorkoutRouteMapViewController.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/RouteMapScene/WorkoutRouteMapViewModel.swift
iOS/Projects/Shared/CommonNetworkingKeyManager/Sources/TNKeychainInterceptor.swift

|Name|
|:-:|
|(image here)|
<br/><br/>
- `static let defaultPolyLineLocationList: [[Double]] = [[37.559986, 126.975230]]`
- @WhiteHyun 에게 폴리라인이 한개 일 때 발생하는 현상에 대해서 전달
<br/><br/>
<br/><br/>
---
- Closed: #331

[GWL-331] LocationData가 Polyline을 그릴 수 없을 만큼 데이터 갯수가 작을 때 FatalError가 발생하는 버그 수정

---

BackEnd/src/auth/auth.controller.ts
BackEnd/src/auth/auth.service.ts
BackEnd/src/auth/exceptions/auth.exception.ts
BackEnd/src/common/exceptionFilters/httpException.filter.ts

- 첫 로그인시 http code 201
- 첫 로그인이 아니라면 http code 200 -> access token, refresh token 발급
@POST() 응답은 무조건 http code가 201이다. 
그래서 data에 따라서 http code를 변경하기 위해서 @Res()를 사용했는데 
이 방법은 global interceptor를 무시한다.
그래서 global exception filter에 걸리게 
예외 처리로 해줬다.
첫 로그인이 아니라면 throw new NotFirstLoginException(data); 코드를 실행했고
exception filter에서는 status가 200이라면 응답 값에 data 부분이 null이 아닌 data를 넣어주는 식으로 구현했다.
---
- Closed: #336

[GWL-336] fix: appleSignIn 응답 값에 따른 http code 설정

---

iOS/Projects/App/WeTri/Sources/Application/AppDelegate.swift
iOS/Projects/App/WeTri/Sources/TabBarScene/Coordinator/TabBarCoordinator.swift
iOS/Projects/Features/SignUp/Sources/Data/Repository/ImageFormRepository.swift
iOS/Projects/Features/SignUp/Sources/Presentation/SignUpProfileScene/SignUpProfileViewController.swift
iOS/Projects/Features/SignUp/Sources/Presentation/SignUpProfileScene/ViewModel/SignUpProfileViewModel.swift

|결과 화면|
|:-:|
|<img src="https://github.com/JongPyoAhn/Python/assets/68585628/4dc2a781-6789-4da8-bffa-0504b000fb68">|
<br/><br/>
- ViewModel에서 이미 모든 코드를 구성해놓아서 Error를 VC까지 가져갈 방법이 없는것 같은데... 어떻게..?
- 승현님이 알려주시는 방법대로 Publisher를 여러 갈래로 나누어서 처리할 수 있었습니다.
<br/><br/>
❌
<br/><br/>
---
- Closed: #320

[GWL-320] ResponseCode에 따른 이미지 재설정 얼럿 추가

---

iOS/Projects/Features/Record/Sources/Presentation/Common/Coordinator/RecordFeatureCoordinator.swift
iOS/Projects/Features/Record/Sources/Presentation/Common/Coordinator/WorkoutSessionCoordinator.swift
iOS/Projects/Features/Record/Sources/Presentation/CountDownBeforeWorkoutScene/ViewController/CountDownBeforeWorkoutViewController.swift
iOS/Projects/Features/Record/Sources/Presentation/CountDownBeforeWorkoutScene/ViewModel/CountDownBeforeWorkoutViewModel.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutEnvironmentScene/ViewController/WorkoutEnvironmentSetupViewController.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutEnvironmentScene/ViewController/WorkoutSelectViewController.swift
iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/RouteMapScene/WorkoutRouteMapViewController.swift

|버그|수정본|
|:-:|:-:|
|![RPReplay_Final1702200138](https://github.com/boostcampwm2023/iOS08-WeTri/assets/103064352/9fe20a04-61c5-447b-a595-92e42bbcb829)|![RPReplay_Final1702201492](https://github.com/boostcampwm2023/iOS08-WeTri/assets/103064352/ba740b59-d3e7-4eb3-9b75-122987852571)|
<br/><br/>
<br/>
|운동 결과 화면| 홈으로 눌렀을 때| 
|:-:|:-:|
|![Simulator Screenshot - iPhone 15 Pro - 2023-12-10 at 20 50 47](https://github.com/boostcampwm2023/iOS08-WeTri/assets/103064352/4194f319-91e5-453c-b049-9bc3cb045164)| ![Simulator Screenshot - iPhone 15 Pro - 2023-12-10 at 20 52 25](https://github.com/boostcampwm2023/iOS08-WeTri/assets/103064352/6f2fc8e3-8c51-4f47-8069-66d39f8fbefb) |
<br/><br/>
<br/><br/>
---
- Closed: #334

[GWL-334] 카운트다운 화면, WorkoutSession, WorkoutSummery 화면에서 TabBar 보이는 버그 수정

---

iOS/Projects/App/WeTri/Sources/CommonScene/Coordinator/AppCoordinator.swift
iOS/Projects/App/WeTri/Sources/TabBarScene/Coordinator/TabBarCoordinator.swift
iOS/Projects/Features/Profile/Project.swift
iOS/Projects/Features/Profile/Sources/Data/DTO/PostsRequestDTO.swift
iOS/Projects/Features/Profile/Sources/Data/DTO/PostsResponseDTO.swift
iOS/Projects/Features/Profile/Sources/Data/Repositories/KeychainRepository.swift
iOS/Projects/Features/Profile/Sources/Data/Repositories/ProfileRepository.swift
iOS/Projects/Features/Profile/Sources/Domain/Interfaces/KeychainRepositoryRepresentable.swift
iOS/Projects/Features/Profile/Sources/Domain/UseCases/LogoutUseCase.swift
iOS/Projects/Features/Profile/Sources/Domain/UseCases/Protocol/LogoutUseCaseRepresentable.swift
iOS/Projects/Features/Profile/Sources/Presentation/Coordinator/ProfileCoordinator.swift
iOS/Projects/Features/Profile/Sources/Presentation/SettingsScene/SettingsViewController.swift
iOS/Projects/Features/Profile/Sources/Presentation/SettingsScene/SettingsViewModel.swift

|로그아웃 기능 화면|
|:-:|
|![RPReplay_Final1702227357](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/10c669e3-5d3b-41be-8082-cb8b6bad074c)|
- 프로필 API가 변경되어 서버에 맞게 수정했습니다.
- 로그아웃 버튼이 눌리면 로그아웃 화면으로 넘어가도록 구현했습니다.
---
- Closed: #351

[GWL-351] 프로필 API 변경에 따른 코드 수정 + 로그아웃 기능 추가

---

iOS/Projects/App/WeTri/Sources/TabBarScene/Coordinator/TabBarCoordinator.swift
iOS/Projects/Features/Profile/Project.swift
iOS/Projects/Features/Profile/Sources/Data/Repositories/ProfileSettingsRepository.swift
iOS/Projects/Features/Profile/Sources/Domain/Entities/Profile.swift
iOS/Projects/Features/Profile/Sources/Domain/Interfaces/ProfileSettingsRepositoryRepresentable.swift
iOS/Projects/Features/Profile/Sources/Domain/UseCases/ProfileSettingsUseCase.swift
iOS/Projects/Features/Profile/Sources/Domain/UseCases/Protocol/ProfileSettingsUseCaseRepresentable.swift
iOS/Projects/Features/Profile/Sources/Presentation/Coordinator/ProfileCoordinator.swift
iOS/Projects/Features/Profile/Sources/Presentation/ProfileSettingsScene/ProfileSettingsHeaderView.swift
iOS/Projects/Features/Profile/Sources/Presentation/ProfileSettingsScene/ProfileSettingsViewController.swift
iOS/Projects/Features/Profile/Sources/Presentation/ProfileSettingsScene/ProfileSettingsViewModel.swift

|Name|
|:-:|
|![RPReplay_Final1702256213](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/3474be79-4e0c-433a-9d8f-9db5b0b35d1d)|
<br/><br/>
프로필 설정 화면이 기본값으로 설정되는 것을 수정했습니다. UserDefaults로 사용자의 데이터 정보를 가져와 뿌려줍니다.
---
- Closed: #353

[GWL-353] 프로필 설정 화면 시 사용자 정보 데이터 파싱

---

iOS/Projects/Features/SignUp/Sources/Presentation/SignUpProfileScene/SignUpProfileViewController.swift

❌
<br/><br/>
- 선택하자마자 사라지지 않았던 이유는 선택 시, dismiss를 카메라부분 로직에만 적용해서 그랬습니다. 🥲
- 확인버튼을 추가하기위해 알아보고 코드를 작성하던 도중, 문득 앨범에서 선택하면 사라지지 않는 현상때문에 해당 트러블에 대한 피드백을 받았다는 생각이 들었습니다. 그래서 확인해보니 앨범에서 사진을 선택하면 피커가 사라지지 않았고 해당현상을 개선하였습니다.
<br/><br/>
❌
<br/><br/>
---
- Closed: #362

[GWL-362] 앨범에서 이미지 선택 시, 이미지피커가 사라지지 않는 문제 개선

---

iOS/Projects/Features/Record/Resources/Persistency/Records.json
iOS/Projects/Features/Record/Sources/Data/DTO/RecordResponseDTO.swift
iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutRecordsRepository.swift
iOS/Projects/Features/Record/Sources/Presentation/RecordScene/CollectionViewCell/WorkoutInformationCollectionViewCell.swift
iOS/Projects/Features/Record/Sources/Presentation/RecordScene/ViewController/RecordContainerViewController.swift
iOS/Projects/Features/Record/Sources/Presentation/RecordScene/ViewController/RecordListViewController.swift

|iPhone SE 2nd generation|
|:-:|
|<img src="https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/e5a448b2-60c5-497d-8a2d-df2f89f6701d" width="33%"/>|
- 기록 화면에서 기록을 가져오지 못하는 버그가 있었고, 서버의 API와 클라이언트에서 설정한 API 모델이 달라 발생한 문제였습니다.
- 서버의 데이터 응답 모델을 맞추고, Mock json도 업데이트했습니다.
- 코드를 약간 다듬었습니다.
<br/><br/>
---
- Closed: #375

[GWL-375] 운동 기록 리스트 fetching 안되는 버그 수정

---

iOS/Projects/Features/Record/Sources/Presentation/WorkoutPeerMatchingScene/ViewController/WorkoutPeerRandomMatchingViewController.swift

|매칭되는 화면 수정|
|:-:|
|![Simulator Screen Recording - iPhone 15 Pro - 2023-12-12 at 00 17 35](https://github.com/boostcampwm2023/iOS08-WeTri/assets/103064352/5d57e783-f029-4882-88eb-b3fb8c4fd456)|
<br/><br/>
- removeFIrst가 O(n) 이지만 n = 3 이고, data가 String 이라 무시해도 될 것이라 생각했습니다.
<br/><br/>
<br/><br/>
---
- Closed: #388

[GWL-388] 매칭 될 때 실제 매칭되는 화면처럼 수정

---

iOS/Projects/App/WeTri/Sources/Application/SceneDelegate.swift
iOS/Projects/Features/SignUp/Sources/Data/DTO/NickNameDuplicateRequestDTO.swift
iOS/Projects/Features/SignUp/Sources/Data/Repository/SignUpRepository.swift
iOS/Projects/Features/SignUp/Sources/Domain/Interfaces/SignUpRepositoryRepresentable.swift
iOS/Projects/Features/SignUp/Sources/Domain/UseCase/SignUpUseCase.swift
iOS/Projects/Features/SignUp/Sources/Presentation/SignUpProfileScene/SignUpProfileViewController.swift
iOS/Projects/Features/SignUp/Sources/Presentation/SignUpProfileScene/View/NickNameDuplicatingCheckerView.swift
iOS/Projects/Features/SignUp/Sources/Presentation/SignUpProfileScene/ViewModel/SignUpProfileViewModel.swift

|결과 화면|
|:-:|
|<img src="https://github.com/JongPyoAhn/Python/assets/68585628/9cf85964-5abc-4a0a-a719-44b11d860492" width="300" height="500">|
<br/><br/>
중복체크 버튼을 이용하는 방식과 닉네임을 입력할 때 특정조건이 만족하면 닉네임 중복체크를 확인하는 방법이 있었습니다.
후자를 선택했는데요. Combine에는 Debounce라는 좋은 기능이 있기 때문입니다.
Debounce는 입력이 종료되고나서 설정한 시간후에 마지막으로 들어온 스트림을 실행시켜줍니다.
<br/><br/>
❌
<br/><br/>
---
- Closed: #(issue-here)

[GWL-306] 닉네임 중복검사 기능 추가

---

iOS/Projects/Features/Onboarding/Sources/Presentaion/ViweController/OnboardingViewController.swift
iOS/Projects/Shared/DesignSystem/Resources/Colors.xcassets/Main-03.colorset/Contents.json
iOS/Projects/Shared/DesignSystem/Sources/UIButtonConfiguration+Main.swift
iOS/Projects/Shared/DesignSystem/Sources/UIButtonConfiguration+MainCircular.swift

온보딩 화면일 때 텍스들이 희미하게 보이는 버그를 수정했습니다. 
|Name|
|:-:|
|![image](https://github.com/boostcampwm2023/iOS08-WeTri/assets/103064352/3c736004-1cd3-4bbc-92eb-bd88eab9726c)|
<br/><br/>
<br/><br/>
<br/><br/>
---
- Closed: #393

[GWL- 393 (HotFix)] 온보딩 화면 텍스트 희미한 문제 해결

---

iOS/Projects/Features/Record/Sources/Data/DTO/RecordResponseDTO.swift
iOS/Projects/Features/Record/Sources/Presentation/RecordScene/ViewController/RecordListViewController.swift

- km를 `m`로 수정
- 시간대가 15시간 차이나는 이슈 수정
- 서버로부터 데이터를 받아올 때 `Date`타입의 TimeZone이 UTC로 처리되는 이슈가 존재했고,
dateFormatter의 TimeZone을 `UTC`로 설정해서 같은 시간대로 String파싱이 가능하도록 설정함
---
- Closed: #396

[GWL-396] 시간대 15시간 차이나는 버그 수정

---

iOS/Projects/Shared/CombineCocoa/Sources/GestureSubscription.swift
iOS/Projects/Shared/CombineCocoa/Sources/UIView+Publisher.swift

|로그|실제 코드|
|:-:|:-:|
|![스크린샷 2024-01-11 오후 2 16 19](https://github.com/boostcampwm2023/iOS08-WeTri/assets/103064352/de0a2de0-3493-4e41-a1d8-89444c2460e4)|![스크린샷 2024-01-11 오후 2 16 17](https://github.com/boostcampwm2023/iOS08-WeTri/assets/103064352/2d154aec-27c6-47d4-bbfa-c37f126f682e)|
<br/><br/>
- Event처럼 달고 싶은데 어떻게 하면 좋을지 고민.
- GestureSubscription에서 Subscriber를 받아서 gesture에 addTarget을 통해 Subscriber에게 이벤트를 전달하는 방식으로 만듦
- 현재는 Gesture를 넘기는 것은 일차원적인 Gesture 밖에 없음.
- 만약 CustomGesture를 넘길려면 [레퍼런스](https://jllnmercier.medium.com/combine-handling-uikits-gestures-with-a-publisher-c9374de5a478) 같이 하면 되는데, 이렇게 하는 것에 메리트를 못 느껴서 다음과 같이 작성
- Test에 관해서 고민했지만, CombineComunity에 CombineCocoa 에도 Gesture에 관한 Test가 없었음... 
- 따라서 UnitTest를 통해서 접근해도 좋을 것 같다는 생각이 들었음(언젠간 하겠지...?)
<br/><br/>
- …

[GWL-445] CombineCocoa GesturePublisher 생성
