iOS/.github/pull_request_template.md
- 없음
<br/><br/>
- PR 작성 시 일관된 문서를 유지하고자 템플릿을 생성하게 되었습니다.
<br/><br/>
- 없음
<br/><br/>
---
- Closed: #19
=> [GWL-30] PR Template 추가

iOS/Projects/Core/HealthKit/Project.swift, iOS/Projects/Core/Network/Project.swift, iOS/Projects/Core/Persistence/Project.swift, iOS/Projects/Domain/Entity/Project.swift, iOS/Projects/Domain/Repositories/Project.swift, iOS/Projects/Domain/Usecase/Project.swift, iOS/Projects/Features/Record/Project.swift, iOS/Projects/Shared/DesignSystem/Project.swift
<br/><br/>
- Modular Architecture 선택 
- Clean Architecture구조로 모듈화를 선택할 시 Import해야하는 target의 갯수가 상당히 많음
- Modular Architecture는 상기 Clean Architecture 보다 복잡성이 감소
- Modular Architecture는 Clean Architecture 보다 모듈화 용이
- clean 에 비해서 **빌드 속도를 향상, 재사용 가능한 모듈을 프레임워크로 사용, 협업 용이**
<br/><br/>
- https://tech.olx.com/modular-architecture-in-ios-c1a1e3bff8e9
- https://github.com/kudoleh/iOS-Modular-Architecture
- https://github.com/kudoleh/iOS-Clean-Architecture-MVVM
---
- Closed: #2
=> [GWL-8] MVVM-C + Clean Architecture 초기 적용

.github/workflows/BackEnd_CI.yml
<br/><br/>
- BackEnd CI를 구현했습니다.
<br/><br/>
- [git actions CI](https://ji5485.github.io/post/2021-06-06/build-ci-cd-pipeline-using-github-actions/)
---
- Closed: #21
=> [GWL-31] BackEnd CI 적용

BackEnd/package-lock.json, BackEnd/package.json, BackEnd/src/app.module.ts, BackEnd/src/config/swagger.config.ts, BackEnd/src/config/typeorm.config.ts, BackEnd/src/config/winston.config.ts, BackEnd/src/main.ts, BackEnd/src/middlewares/logger.middleware.ts
<br/><br/>
- Swagger를 설치 및 적용
- Logger 적용 및 Winston을 이용한 logs 파일에 저장, log파일이 쌓일 경우 압축해서 저장을 하게된다.
- TypeORM에서 Async를 제거했다.
<br/><br/>
- [Nestjs](https://wikidocs.net/158639)
- [Swagger 모듈 설치](https://docs.nestjs.com/openapi/introduction)
---
- Closed: #42
=> [GWL-43] Swagger, Logger 적용 및 TypeORM Async 제거

iOS/Projects/Features/Record/Sources/WorkoutSelectScene/View/WorkoutCardCell.swift, iOS/Projects/Features/Record/Sources/WorkoutSummary/ParticipantsCollectionViewCell.swift, iOS/Projects/Features/Record/Sources/WorkoutSummary/WorkoutSummaryViewController.swift, iOS/Projects/Shared/DesignSystem/Sources/DesignSystemColor.swift
|Diff|
|:-:|
|![image](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/b4612a91-15f3-4b34-b822-2621dca1f949)|
<br/><br/>
Background가 하나의 단어인데, G에 대문자가 더 들어가있었고, 불ㅡ편해서 바로 수정했습니다. 😂
<br/><br/>
- 없음
<br/><br/>
---
=> [GWL-5] DesignSystem 변수명 수정

iOS/Projects/Features/Record/Sources/WorkoutSelectScene/View/WorkoutCardCell.swift, iOS/Projects/Shared/DesignSystem/Sources/UIButtonConfiguration+Main.swift, iOS/Projects/Shared/DesignSystem/Sources/UIButtonConfiguration+MainCircular.swift
- 없음
<br/><br/>
- DesignSystem 모듈에서 UIButton 쪽의 Color가 수정되지 않은 것을 발견했습니다. 왜 빌드되었었는지는 모르겠으나.. 보자마자 바로 고쳤습니다.
<br/><br/>
- #65
=> [GWL-5] Design System Color 변경되지 않는 코드 수정

.github/workflows/iOS_CI.yml
- 없음
<br/><br/>
- `-name`바로 밑에 `-uses`가 들어있는데 `uses`로 수정해야합니다.. 어쩌다보니 잘못들어갔네요 😔
- #63
=> [GWL-54] iOS CI Yaml 수정

BackEnd/src/app.controller.spec.ts, BackEnd/src/app.module.ts, BackEnd/src/auth/auth.controller.ts, BackEnd/src/auth/auth.module.ts, BackEnd/src/auth/guard/bearerToken.guard.ts, BackEnd/src/profiles/decorator/profile.decorator.ts, BackEnd/src/records/dto/create-exerciseLog.dto.ts, BackEnd/src/records/entities/records.entity.ts, BackEnd/src/records/records.controller.ts, BackEnd/src/records/records.module.ts, BackEnd/src/records/records.service.ts
|api 실행 결과|
|:-:|
|<img width="543" alt="스크린샷 2023-11-21 오후 3 37 10" src="https://github.com/boostcampwm2023/iOS08-WeTri/assets/89844585/e6c48d38-d155-43c7-9897-b94ee9238cd0">|
<br/><br/>
`api/v1/records` POST 요청하면 운동 기록을 저장합니다. 
권한이 필요한 함수는  @UseGuards(AccessTokenGuard) 사용해주세요.
그리고 @Profile은 파라미터 데코레이터입니다. 사용자의 profile 정보를 담아주는 역할을 합니다. (이 데코레이터를 적용하려면 꼭 @UseGuards(AccessTokenGuard) 선행되어야 됨)
<br/><br/>
<br/><br/>
---
- Closed: #73
=> [GWL-59] 유저가 운동을 마친 후 기록하는 API 요청

.github/workflows/BackEnd_CD.yml, .github/workflows/BackEnd_CI.yml, BackEnd/Dockerfile
<br/>
- self-hosted로 bastion-host의 IP를 좁힐 수 있었지만, 이미지를 빌드하는 환경은 ARM64 pull해서 run하는 환경은 linux AMD64임을 알게되었습니다.
- appleboy는 일단 사용이 불가능해, sshpass로 대체하였습니다.
- 아직 많이 미흡하고 손댈 부분이 많지만, 클라우드와 배포는 여기까지만 두고, 기능개발 들어갈게욤
<br/>
<br/>
- [buildx](https://buildabetterworld.tistory.com/178)
<br/>
---
- Closed: #93
=> [GWL-71] self-hosted Runner로 변경에 따른 CD 수정

BackEnd/src/auth/auth.controller.ts, BackEnd/src/auth/auth.service.ts, BackEnd/src/profiles/entities/profiles.entity.ts, BackEnd/src/profiles/profiles.service.ts, BackEnd/src/records/dto/create-exerciseLog.dto.ts, BackEnd/src/records/entities/records.entity.ts, BackEnd/src/records/exceptions/records.exception.ts, BackEnd/src/records/records.controller.ts, BackEnd/src/records/records.service.ts
|운동 기록하면 recordId 반환|
|:-:|
|<img width="385" alt="스크린샷 2023-11-22 오후 12 15 34" src="https://github.com/boostcampwm2023/iOS08-WeTri/assets/89844585/b31be30c-6e07-4f2e-bccc-8fef28615d91">|
|내 운동 기록 확인하기|
|:-:|
|<img width="535" alt="스크린샷 2023-11-22 오후 3 32 37" src="https://github.com/boostcampwm2023/iOS08-WeTri/assets/89844585/83025764-4d9a-47fb-8742-964b24996f1c">|
|recordId 운동 기록 확인하기|
|:-:|
|<img width="586" alt="스크린샷 2023-11-22 오후 3 31 50" src="https://github.com/boostcampwm2023/iOS08-WeTri/assets/89844585/2282df74-4554-4943-8893-90d20c9d6746">|
<br/><br/>
`api/v1/records/me` -> 내 운동 기록 확인하기
`api/v1/records/{recordId}` -> recordId 운동 기록 확인하기
백엔드 위키 API 명세서 업데이트 했습니다.
<br/><br/>
<br/><br/>
---
- Closed: #71
=> [GWL-57] 유저의 운동 기록 API 요청

iOS/Projects/Features/Record/Project.swift, iOS/Projects/Features/Record/Resources/MockJSON/WorkoutSummary.json, iOS/Projects/Features/Record/Sources/Data/DTO/WorkoutSummaryDTO.swift, iOS/Projects/Features/Record/Sources/Data/Persistency/WorkoutSummary.json, iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutSummaryRepository.swift, iOS/Projects/Features/Record/Sources/Domain/Interfaces/Repositories/WorkoutSummaryRepositoryRepresentable.swift, iOS/Projects/Features/Record/Sources/Domain/UseCases/WorkoutSummaryUseCase.swift, iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/SessionScene/WorkoutSessionViewModel.swift, iOS/Projects/Features/Record/Sources/Presentation/WorkoutSummaryScene/WorkoutSummaryCardView.swift, iOS/Projects/Features/Record/Sources/Presentation/WorkoutSummaryScene/WorkoutSummaryViewController.swift, iOS/Projects/Features/Record/Sources/Presentation/WorkoutSummaryScene/WorkoutSummaryViewModel.swift, iOS/Projects/Shared/DesignSystem/Sources/UIFont+preferredFont.swift
|오류 발생 시|정상적으로 값이 들어왔을 때|
|:-:|:-:|
|![RPReplay_Final1700646830](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/aeff3ea6-e882-42a6-8b27-b6c7318e5501)|![RPReplay_Final1700646862](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/a0b52714-d0cc-4500-8fc4-ec7748aba2ea)|
<br/><br/>
> [!Warning]
>
> 지도를 1:1비율로 가져가면서 버튼이 밑으로 나가버리네요.. 이건 빠르게 고쳐보겠습니다. 🛠️
- Mock Data를 가지고 UI를 구성하는 단방향 흐름을 구현해보았습니다.
- MockSession을 이용했어요. 이 부분은 테스트 코드다 보니 커밋에 넣지 않았어요.
- 테스트하고 싶다면 밑에 Test Code를 참고해주세요.
- GWResponse를 다함님께서 구현해주셔서 따로 코드에 추가하지 않았어요.
- RecordFeature가 Resources를 갖도록 재설정했어요.
- Mock Data를 띄워주기 위함인데요.. 다함님께서 Sources에서 처리하셨던데 어떻게 하셨는지 궁금합니다 ㅎㅎ.. `make generate`를 할 때 인식을 못하더라고요.
- 그래서 Resources폴더에 json을 넣어두었습니다.
- 운동 요약화면을 보여줄 때 운동 기록 데이터를 서버로부터 가져와야하는데요. 운동 기록 ID를 이전 페이지에서 받아와서 데이터 …
=> [GWL-27] 운동 결과 화면 흐름 구현

iOS/Projects/Features/Record/Resources/MockJSON/WorkoutSession.json, iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutRecordRepository.swift, iOS/Projects/Features/Record/Sources/Domain/Entities/WorkoutHealth.swift, iOS/Projects/Features/Record/Sources/Domain/Interfaces/Repositories/WorkoutRecordRepositoryRepresentable.swift, iOS/Projects/Features/Record/Sources/Domain/UseCases/WorkoutRecordUseCase.swift, iOS/Projects/Features/Record/Sources/Presentation/Common/Coordinator/Protocol/WorkoutSessionCoordinating.swift, iOS/Projects/Features/Record/Sources/Presentation/Common/Coordinator/WorkoutSessionCoordinator.swift, iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/RouteMapScene/WorkoutRouteMapViewController.swift, iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/SessionScene/WorkoutSessionViewController.swift, iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/WorkoutSessionContainerViewController.swift, iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/WorkoutSessionContainerViewModel.swift, iOS/Projects/Features/Record/Sources/Presentation/WorkoutSummaryScene/WorkoutSummaryViewController.swift
|navigation bar hidden false|navigation bar hidden true|
|:-:|:-:|
|![Screenshot 2023-11-26 at 4 41 16 PM](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/290874ab-134d-4d9a-9ab6-eae6c0c29fed)|![Screenshot 2023-11-26 at 4 44 03 PM](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/d2f8b7c1-5733-4a0d-bbe5-154d69bcf1b0)|
|![Simulator Screen Recording - iPhone 15 Pro Max - 2023-11-26 at 16 40 09](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/cec44e37-7fbf-49cd-aef0-aa4430e86076)|![Simulator Screen Recording - iPhone 15 Pro Max - 2023-11-26 at 16 44 34](https://github.com/boostcampwm2023/iOS08-WeTri/assets/57972338/3197c790-0147-4457-9051-e657adadef24)|
<br/><br/>
운동세션에는 세 개의 ViewController가 존재합니다.
1. `WorkoutSessionContainerViewController`: 뷰 …
=> [GWL-15] 운동 세션 Flow와 운동 요약 화면 이동 처리

.github/workflows/BackEnd_CI.yml, BackEnd/package-lock.json, BackEnd/package.json, BackEnd/src/admin/admin.controller.ts, BackEnd/src/admin/admin.module.ts, BackEnd/src/admin/admin.service.ts, BackEnd/src/admin/dto/login.dto.ts, BackEnd/src/admin/entities/admin.entity.ts, BackEnd/src/admin/exceptions/admin.exception.ts, BackEnd/src/app.module.ts, BackEnd/src/profiles/entities/profiles.entity.ts, package-lock.json
|Admin 로그인 스웨거|
|:-:|
|<img width="1429" alt="스크린샷 2023-11-27 오후 3 29 08" src="https://github.com/boostcampwm2023/iOS08-WeTri/assets/89844585/964cc6b5-26ed-415a-ae9d-c753b6b095e4">|
<br/><br/>
- `api/v1/admin/login` Post 요청 => body에 adminId, adminPw를 담아서 보내면 검증 후 accessToken, refreshToken을 반환합니다.
<br/><br/>
<br/><br/>
---
- Closed: #140
=> [GWL-140] 어드민 계정 생성, 로그인 구현

BackEnd/src/admin/entities/admin.entity.ts, BackEnd/src/auth/auth.service.ts, BackEnd/src/live-workouts/events/events.gateway.ts, BackEnd/src/live-workouts/matches/dto/random-match.dto.ts, BackEnd/src/live-workouts/matches/matches.service.spec.ts, BackEnd/src/profiles/entities/profiles.entity.ts, BackEnd/src/workouts/dto/workout-response.dto.ts, BackEnd/src/workouts/workouts.controller.ts, BackEnd/src/workouts/workouts.module.ts, BackEnd/src/workouts/workouts.service.spec.ts, BackEnd/src/workouts/workouts.service.ts
|Name|
|:-:|
|![image](https://github.com/boostcampwm2023/iOS08-WeTri/assets/56383948/edf97146-1572-4c45-85e9-9ca8a676b2e1)|
|![image](https://github.com/boostcampwm2023/iOS08-WeTri/assets/56383948/5aef7e24-044b-4397-8d5e-21dd6898ef64)|
<br/><br/>
<br/>
- workout과, id를 리턴하도록 로직 변경 및 Swagger를 변경했습니다.
- findAllWorkouts 메서드에 대해서 테스트 코드를 작성했습니다.
<br/>
<br/><br/>
---
- Closed: #137
=> [GWL-137] Workout API 수정, 테스트 코드 작성 및 Swagger 수정 

iOS/Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift, iOS/Projects/App/WeTri/Project.swift, iOS/Projects/App/WeTri/WeTri.entitlements, iOS/Projects/Core/Keychain/Project.swift, iOS/Projects/Core/Keychain/Sources/Keychain.swift, iOS/Projects/Core/Keychain/Sources/Protocol/KeyChaining.swift, iOS/Projects/Core/Keychain/Tests/KeychainTests.swift, iOS/Projects/Core/Keychain/Tests/Mock/MockKeychain.swift
|Name|
|:-:|
|<img src = "https://github.com/JongPyoAhn/Python/assets/68585628/f9604dbb-07b8-42fb-b0b9-aeeed130c30a">|
<br/><br/>
- keychain의 단위테스트는 어떻게 진행해야할까?
- keychain으로 단위테스트를 진행하게되면 값을 저장하거나 불러올 때, `-34018`에러가 발생하게 됩니다. 이는 키체인에 접근할 수 있는 보안권한이 없기 때문인데요. 따로 샘플프로젝트를 만들어서 아무설정도안하고 진행했을때는 잘 진행되는걸 확인했습니다. 유추할 수 있는건 TestCode를 작성할 때, KeyChain에 접근하는것에 대한 문제가 있는것 같습니다. 그래서 테스트코드를 블랙박스테스트로 따로 MockKeychain을 만들어서 진행하였습니다.
<br/><br/>
- [Key체인 사용법](https://velog.io/@rose6649/IOS-Keychain-%ED%82%A4%EC%B2%B4%EC%9D%B8-%EC%82%AC%EC%9A%A9%EB%B2%95)
- [[2]](https://adora-y.tistory.com/entry/iOS-KeyChain%EC%9D%B4%EB%9E%80-Swift%EC%BD%94%EB%93%9C%EB%A5%BC-%ED%86%B5%ED%95%B4-%EC%82%B4%ED%8E%B4%EB%B3%B4%EA%B8%B0)
- [Key체인 공식문서](https://developer.apple.com/documentation/security/keychain_services/keychain_ite …
=> [GWL-150] Keychain 모듈 작성

iOS/Projects/Features/Record/Sources/Domain/UseCases/CountDownBeforeWorkoutStartTimerUseCase.swift, iOS/Projects/Features/Record/Sources/Domain/UseCases/OneSecondsTimerUseCase.swift, iOS/Projects/Features/Record/Sources/Domain/UseCases/TimerUseCase.swift, iOS/Projects/Features/Record/Tests/TimerTest.swift
N/A
<br/><br/>
- Timer를 Protcol로 관리하기에는 뭔가 석연치 않은 부분이 있었음
- countDown도 타이머고, Stopwatch도 타이머가 필요한데 이를 어떻게 묶으면 좋을지 고민
- 따로 class를 빼서 상속 가능하게 만듦으로서 확장에 유리하게 만듦
- 이를 통해서 StopWatch타이머와, CountDown타이머를 리팩토링
- 텟케성공률 100
<br/><br/>
<br/><br/>
---
- Closed: #10
=> [GWL-10]운동 세션화면 스톱워치 설정하기 (UseCase로 구현 완료, 테스트코드 작성)

iOS/Projects/Features/Record/Sources/Presentation/Common/Coordinator/Protocol/WorkoutEnvironmentSetUpCoordinating.swift, iOS/Projects/Features/Record/Sources/Presentation/Common/Coordinator/Protocol/WorkoutSessionCoordinating.swift, iOS/Projects/Features/Record/Sources/Presentation/Common/Coordinator/RecordFeatureCoordinator.swift, iOS/Projects/Features/Record/Sources/Presentation/Common/Coordinator/WorkoutEnvironmentSetUpCoordinator.swift, iOS/Projects/Features/Record/Sources/Presentation/Common/Coordinator/WorkoutSessionCoordinator.swift, iOS/Projects/Features/Record/Sources/Presentation/CountDownBeforeWorkoutScene/ViewController/CountDownBeforeWorkoutViewController.swift, iOS/Projects/Features/Record/Sources/Presentation/CountDownBeforeWorkoutScene/ViewModel/CountDownBeforeWorkoutViewModel.swift
N/A
<br/><br/>
N/A 
- https://github.com/boostcampwm2023/iOS08-WeTri/pull/48
<br/><br/>
---
- Closed: #155
=> [GWL-155] RecordFeture coordinating 화면 연결

iOS/Projects/Features/Login/Sources/Data/Repositories/AuthorizationRepository.swift, iOS/Projects/Features/Login/Sources/Data/Repositories/KeychainRepository.swift
❌
<br/><br/>
- #163 
<br/><br/>
❌
<br/><br/>
---
- Closed: #156
=> [GWL-156] 애플로그인 버튼 및 비즈니스 로직 구현

BackEnd/src/records/dto/create-exerciseLog.dto.ts, BackEnd/src/records/dto/record-response.dto.ts, BackEnd/src/records/entities/records.entity.ts, BackEnd/src/records/records.controller.ts
|Record|
|:-:|
|![image](https://github.com/boostcampwm2023/iOS08-WeTri/assets/56383948/37e10502-e097-4e14-a22c-05d5cfe8219f)|
<br/>
<br/>
<br/>
- records가 노션에 업데이트 되었습니다
- 승현님과 상의 후 개선에 들어갔습니다.
<br/>
<br/><br/>
---
- Closed: #138
=> [GWL-138] Record API 수정 및 Swagger 수정

BackEnd/src/auth/auth.service.ts, BackEnd/src/auth/exceptions/auth.exception.ts, BackEnd/src/records/entities/records.entity.ts
- reocrd table에 workoutId 추가 (workout table의 기본키를 의미함)
- accessToken, refreshToken 만료, 변조 exception 처리
---
- Closed: #192
=> [GWL-192] fix: record table에 workoutId 추가, accessToken, refreshToken 만료, 변조 exception 처리

BackEnd/src/posts/dto/delete-post-response.dto.ts, BackEnd/src/posts/dto/get-post-response.dto.ts, BackEnd/src/posts/dto/get-posts-response.dto.ts, BackEnd/src/posts/dto/update-post.dto.ts, BackEnd/src/posts/entities/posts.entity.ts, BackEnd/src/posts/exceptions/posts.exception.ts, BackEnd/src/posts/posts.controller.ts, BackEnd/src/posts/posts.service.ts, BackEnd/src/users/users.controller.ts, BackEnd/src/users/users.module.ts
- `api/v1/posts/{id}` -> 특정 id의 게시글을 가져옴.
```json
{
"code": null,
"errorMessage": null,
"data": {
"id": 5,
"publicId": "d5cd7b66-7ee6-4453-a73e-026126861e96",
"content": "안녕하세요 누구 누구 입니다.",
"like": null,
"createdAt": "2023-12-03T13:47:08.677Z",
"updatedAt": "2023-12-03T13:47:08.677Z",
"deletedAt": null,
"postUrl": "https://www.naver.com"
}
}
```
- `api/v1/posts/public-id/d5cd7b66-7ee6-4453-a73e-026126861e96?where__id__less_then=17&order__createdAt=DESC&take=5` -> 특정 유저의 게시글을 가져온다. (pagination 활용 각 쿼리 필수가 아님)
```json
{
"code": null,
"errorMessage": null,
"data": {
"items": [
{
"id": 16,
"publicId": "d5cd7b66-7ee6-4453-a73e-026126861e96",
"content": "안녕하세요 누구 누구 입니다.",
"like": null,
"createdAt": "2023-12-04T05:14:39.679Z",
"updatedAt": "2023-12-04T05:14:39.679Z",
"deletedAt": null, …
```
=> [GWL-223] feat: Post api 마무리 하기

iOS/Projects/App/WeTri/Sources/Application/SceneDelegate.swift, iOS/Projects/Features/Record/Sources/Presentation/RecordScene/CollectionViewCell/CalendarCollectionViewCell.swift, iOS/Projects/Features/Record/Sources/Presentation/RecordScene/CollectionViewCell/WorkoutInformationCollectionViewCell.swift, iOS/Projects/Features/Record/Sources/Presentation/RecordScene/View/NoRecordsView.swift, iOS/Projects/Features/Record/Sources/Presentation/RecordScene/ViewController/RecordCalendarViewController.swift, iOS/Projects/Features/Record/Sources/Presentation/RecordScene/ViewController/RecordContainerViewController.swift, iOS/Projects/Features/Record/Sources/Presentation/RecordScene/ViewController/RecordListViewController.swift
|다크 모드|화이트 모드|
|:-:|:-:|
|<img src="https://github.com/JongPyoAhn/Python/assets/68585628/155c923b-32d3-46c4-a256-fa6677df94e5" width="300" height="500">|<img src="https://github.com/JongPyoAhn/Python/assets/68585628/709bca0e-df74-4e51-b432-56be3251b5e4" width="300" height="500">|
<br/><br/>
❌
<br/><br/>
❌
<br/><br/>
---
- Closed: #236
=> [GWL-236] RecordList 다크모드 개선

BackEnd/src/common/common.service.ts, BackEnd/src/main.ts, BackEnd/src/posts/dto/get-post-response.dto.ts, BackEnd/src/posts/dto/get-posts-response.dto.ts, BackEnd/src/posts/entities/posts.entity.ts, BackEnd/src/posts/posts.service.ts, BackEnd/src/profiles/dto/get-profile-posts-response.dto.ts, BackEnd/src/records/records.service.ts
승현님의 요청으로 metaData 수정했습니다.
metaData에는 3가지 속성이 존재합니다.
```json
"metaData": {
"lastItemId": 5,
"isLastCursor": false,
"count": 5
}
```
lastItemId는 말 그대로 item의 마지막 id를 뜻 합니다. 
이 값을 where__id__less_then, where__id__more_then에 value로 넣으면 됩니다.
예를 들면 lastItemId가 5라면 where__id__less_then=5 이 의미는 5보다 작은 이라는 조건을 의미합니다.
기존에는 마지막 커서(페이지)를 구분하기 위해서 마지막 커서라면 lastItemId에 null을 넣어줬지만, 
승현님과 얘기를 나누면서 iOS분들이 처리하기 더 쉬운 방법으로 변경했습니다. 
그래서 마지막 페이지를 구분하기 위한 isLastCursor라는 속성을  metaData에 추가했습니다. 
그러면 lastItemId로는 더 이상 마지막 커서를 구분하지 않기 때문에 네이밍에 맞는 lastItemId를 알 수 있는 용도로만 사용하게끔 변경했습니다.
빈 배열이면 lastItemId는 null 이고, 그렇지 않다면 lastItemId는 마지막 아이템의 id가 들어갑니다.
```json
{
"code": null,
"errorMessage": null,
"data": {
"items": [
{
"id": 16,
"publicId": "d5cd7b66-7ee6-4453-a73e-026126861e96",
"content": "안녕하세요 누구 누구 입니다.", …
```
=> [GWL-241] fix: paginate response metadata 수정

BackEnd/src/records/dto/create-exerciseLog.dto.ts, BackEnd/src/records/dto/record-response.dto.ts, BackEnd/src/records/entities/records.entity.ts
- record 테이블 -> gps, mapCapture 필드 추가
---
- Closed: #265
=> [GWL-265] fix: record entity 수정 mapCapture, gps 추가

BackEnd/src/images/images.controller.ts, BackEnd/src/images/intercepters/wetri-files.interceptor.ts, BackEnd/src/live-workouts/matches/constant/matches.constant.ts, BackEnd/src/live-workouts/matches/dto/create-match.dto.spec.ts, BackEnd/src/live-workouts/matches/dto/random-match.dto.spec.ts, BackEnd/src/live-workouts/matches/dto/random-match.dto.ts, BackEnd/src/live-workouts/matches/matches.controller.ts, BackEnd/src/live-workouts/matches/matches.service.spec.ts, BackEnd/src/live-workouts/matches/matches.service.ts
|Matches API 테스트 코드 작성|
|:-:|
|![image](https://github.com/boostcampwm2023/iOS08-WeTri/assets/56383948/c6954b81-fbef-4623-83bf-d27023b5fb89)|
<br/><br/>
<br/>
- Matches API의 테스트 코드를 작성했습니다.
- 레디스에 expired를 지정해주지 않아서, 이부분을 수정했습니다.
<br/>
<br/><br/>
---
- Closed: #211
=> [GWL-211] Matches API 테스트 코드 작성 및 리팩토링

iOS/Projects/Core/Network/Sources/MultipartFormData.swift
❌
<br/><br/>
[PR](#264 ) 
위 PR에 적혀있습니다!
<br/><br/>
❌
<br/><br/>
---
- Closed: #267
=> [GWL-267]  Trinet Multipart/form-Data 기능 추가

BackEnd/src/live-workouts/matches/matches.service.spec.ts, BackEnd/src/live-workouts/matches/matches.service.ts
<br/><br/>
<br/><br/>
---
- Closed: #275
=> [Fix] 매칭 API matched 리턴 문제 

BackEnd/src/live-workouts/matches/matches.service.ts
<br/><br/>
<br/><br/>
---
- Closed: #277
=> fix: 15초를 더하는데 아닌 15분을 더하는 오류 수정

iOS/.swiftlint.yml, iOS/Projects/Core/Network/Sources/TNProvidable.swift, iOS/Projects/Features/Record/Sources/Data/DTO/IsMatchedRandomPeersRequest.swift, iOS/Projects/Features/Record/Sources/Data/DTO/IsMatchedRandomPeersResponse.swift, iOS/Projects/Features/Record/Sources/Data/DTO/MatchStartRequest.swift, iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutPeerRandomMatchingRepository.swift, iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutSocketRepository.swift, iOS/Projects/Features/Record/Sources/Domain/Entities/WorkoutRealTimeModel.swift, iOS/Projects/Features/Record/Sources/Presentation/Common/Coordinator/RecordFeatureCoordinator.swift, iOS/Projects/Features/Record/Sources/Presentation/Common/Coordinator/WorkoutEnvironmentSetUpCoordinator.swift, iOS/Projects/Features/Record/Sources/Presentation/Common/Coordinator/WorkoutSessionCoordinator.swift, iOS/Projects/Features/Record/Sources/Presentation/WorkoutPeerMatchingScene/ViewController/WorkoutPeerRandomMatchingViewController.swift, iOS/Projects/Features/Record/Sources/Presentation/WorkoutPeerMatchingScene/ViewModel/WorkoutPeerRandomMatchingViewModel.swift, iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/SessionScene/WorkoutSessionViewController.swift, iOS/Projects/Shared/CommonNetworkingKeyManager/Sources/TNKeychainInterceptor.swift, iOS/Projects/Shared/UserInformationManager/Sources/UserInformationManager.swift
|Name|
|:-:|
|(image here)|
<br/><br/>
<br/><br/>
<br/><br/>
---
- Closed: #(issue-here)
=> [GWL-273] 소켓 연결

BackEnd/src/profiles/entities/profiles.entity.ts
<br/>
- profile 테이블의 birthdate를 Date 타입에서 String으로 적용했습니다.
<br/>
<br/><br/>
---
- Closed: #292
=> [Fix] 유저가 signup을 할 때, date 타입이 string이 아닌 문제 발생

BackEnd/src/common/mocks/mocks.ts, BackEnd/src/posts/dto/create-post.dto.ts, BackEnd/src/posts/dto/get-posts-response.dto.ts, BackEnd/src/posts/dto/update-post.dto.ts, BackEnd/src/posts/entities/posts.entity.ts, BackEnd/src/posts/mocks/mocks.ts, BackEnd/src/posts/posts.service.ts, BackEnd/src/posts/queryOptions/get-create-update.queryOptions.ts, BackEnd/src/profiles/dto/get-profile-posts-response.dto.ts, BackEnd/src/profiles/profiles.service.ts
기존 post entity에 postUrl -> imagesUrl
, post response에 profileImage 추가
<br/><br/>
- Closed: #274
=> [GWL-274] fix: posts entity 수정, post response 변경

BackEnd/src/config/typeorm.config.ts, BackEnd/src/records/dto/record-response.dto.ts, BackEnd/src/records/entities/records.entity.ts, BackEnd/src/records/records.service.ts
<br/>
- records 조회에서 workouts 이름이 누락되는 문제 -> 쿼리 빌더를 사용해 leftjoin을 했습니다.
- 로그인시 엑세스 토큰을 받고, 리프래쉬 토큰을 받을 때, 타임아웃 이 걸리는 문제 -> 커넥션 풀을 적용했습니다. (이걸 몰랐네요..)
<br/>
<br/><br/>
---
- Closed: #310 
- Closed: #313
=> [Fix] records 조회에서 workouts 이름이 누락되는 문제, 로그인시 엑세스 토큰을 받고, 리프래쉬 토큰을 받을 때, 타임아웃 이 걸리는 문제

iOS/Projects/App/WeTri/Sources/Application/SceneDelegate.swift, iOS/Projects/Features/SignUp/Sources/Presentation/SignUpGenderBirthScene/SignUpGenderBirthViewController.swift, iOS/Projects/Features/SignUp/Sources/Presentation/SignUpProfileScene/SignUpProfileViewController.swift, iOS/Projects/Features/SignUp/Sources/Presentation/SignUpProfileScene/View/NickNameCheckerView.swift
|성별생년화면|프로필이미지 닉네임 화면|
|:-:|:-:|
|<img src="https://github.com/JongPyoAhn/Python/assets/68585628/9e090a59-0591-4b73-b636-248739312190">|<img src="https://github.com/JongPyoAhn/Python/assets/68585628/21829c5f-61c5-4a7e-a851-2f552f55a192">|
|성별생년화면|프로필이미지 닉네임 화면|
|:-:|:-:|
|<img src="https://github.com/JongPyoAhn/Python/assets/68585628/8c38b663-79a3-4558-91d4-6681ed944cfb">|<img src="https://github.com/JongPyoAhn/Python/assets/68585628/5211de09-63e4-4340-ad3c-901b906338a0">|
<br/><br/>
- DatePicker 에도 IntrinsicSize가 존재합니다.
<br/><br/>
❌
<br/><br/>
---
- Closed: #304
=> [GWL-304] 회원가입 화면 버튼 수정

iOS/Projects/App/WeTri/Sources/Application/SceneDelegate.swift, iOS/Projects/Features/Record/Sources/Presentation/WorkoutEnvironmentScene/ViewController/WorkoutEnvironmentSetupViewController.swift
N/A
<br/><br/>
``` swift
// 중복 데이터 및 타입코드 순서에 맞게 정렬합니다.
let targetTypes = Array(Set(types))
.sorted { $0.typeCode < $1.typeCode }
snapshot.appendItems(targetTypes)
```
<br/><br/>
<br/><br/>
---
- Closed: #323
=> [GWL-323] workoutEnvironment DataSource Sorting문제 해결

iOS/Projects/Features/Record/Sources/Data/DTO/MatchCancelRequest.swift, iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutPeerRandomMatchingRepository.swift, iOS/Projects/Features/Record/Sources/Domain/UseCases/Protocol/WorkoutPeerRandomMatchingRepositoryRepresentable.swift, iOS/Projects/Features/Record/Sources/Domain/UseCases/WorkoutPeerRandomMatchingUseCase.swift, iOS/Projects/Features/Record/Sources/Presentation/WorkoutPeerMatchingScene/ViewModel/WorkoutPeerRandomMatchingViewModel.swift
N/A
<br/><br/>
N/A
<br/><br/>
N/A
<br/><br/>
---
- Closed: #329
=> [GWL-329] Match를 취소 할 때 WorkoutID(운동 번호)를 기재하여 요청

BackEnd/src/records/records.controller.ts
<br/>
- UseGuard가 추가되었습니다.
<br/>
<br/><br/>
---
- Closed: #315
=> [GWL-315] record @UseGuard 추가

iOS/.swiftlint.yml, iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutRecordsRepository.swift, iOS/Projects/Features/Record/Sources/Presentation/RecordScene/ViewController/RecordListViewController.swift, iOS/Projects/Features/Record/Sources/Presentation/RecordScene/ViewModel/RecordListViewModel.swift
|결과 화면|
|:-:|
|<img src="https://github.com/JongPyoAhn/Python/assets/68585628/5c894f03-5900-4613-959b-1f429ece399b">|
<br/><br/>
❌
<br/><br/>
❌
<br/><br/>
---
- Closed: #340
=> [GWL-340] 기록이 존재하지않을 때, 보여줘야하는 커스텀뷰가 안나타나는 현상 개선

iOS/Projects/Features/SignUp/Sources/Domain/UseCase/SignUpUserDefaultsManagerUseCase.swift, iOS/Projects/Features/SignUp/Sources/Presentation/Common/Coordinator/SignUpFeatureCoordinator.swift, iOS/Projects/Features/SignUp/Sources/Presentation/SignUpProfileScene/ViewModel/SignUpProfileViewModel.swift, iOS/Projects/Shared/UserInformationManager/Sources/UserInformationManager.swift
|혼자하기 기능 수정|
|:-:|
|![IMG_7254](https://github.com/boostcampwm2023/iOS08-WeTri/assets/103064352/5abc924a-f03a-4d55-ba9f-08aa5cd6780f)|
<br/><br/>
<br/><br/>
<br/><br/>
---
- Closed: #349
=> [GWL-349] UserDefatuls저장하는 로직 버그 수정

BackEnd/public/index.html
<br/>
- 6주차 ipa 파일 배포입니다~!
<br/>
<br/><br/>
---
- Closed: #355
=> [GWL-355] ipa 파일 배포

.github/workflows/BackEnd_CD_PROD.yml, BackEnd/public/index.html
<br/>
- Production 배포 코드를 수정했습니다!
<br/>
<br/><br/>
---
- Closed: #364
=> [GWL-364] Production 배포 yml 수정!

iOS/Projects/App/WeTri/Sources/Application/SceneDelegate.swift, iOS/Projects/Features/SignUp/Sources/Presentation/SignUpProfileScene/SignUpProfileViewController.swift, iOS/Projects/Features/SignUp/Sources/Presentation/SignUpProfileScene/View/NickNameBoxView.swift
|닉네임 입력하기 전 워닝 레이블 제거|
|:-:|
|<img src = "https://github.com/JongPyoAhn/Python/assets/68585628/89510f9f-c732-45ea-b3ba-5896365d9420" width="300" height="500">|
<br/><br/>
<br/><br/>
❌
<br/><br/>
---
- Closed: #359
=> [GWL-359] 닉네임 관련 버그 픽스

.github/workflows/BackEnd_CD_PROD.yml, BackEnd/public/index.html
<br/>
- 제발 되라!
<br/>
<br/><br/>
---
- Closed: #364
=> [GWL-364] Production 배포 파일 수정

BackEnd/src/records/entities/records.entity.ts
=> [GWL-378] feat: isOptional()추가

BackEnd/src/common/exceptionFilters/httpException.filter.ts
<br/>
- 글로벌 예외처리에서 문자열이 아닌 것을 문자열로 처리
<br/>
<br/><br/>
---
- Closed: #380
=> [GWL-380] 에러메세지가 문자열이 아닌 버그

iOS/Projects/Features/SignUp/Sources/Presentation/SignUpGenderBirthScene/SignUpGenderBirthViewController.swift
|개선 결과|
|:-:|
|<img src = "https://github.com/JongPyoAhn/Python/assets/68585628/5e4d7207-4c9a-445a-8071-5b33cc5676d0" width="300" height="500">|
<br/><br/>
- 어려울줄 알았는데 쉬웠습니다..ㅎㅎ
<br/><br/>
❌
<br/><br/>
---
- Closed: #361
=> [GWL-361] 생년월일 DatePicker 현재날짜 이후 선택되는 현상 개선

BackEnd/src/auth/exceptions/auth.exception.ts, BackEnd/src/profiles/profiles.service.ts
- 닉네임 중복시 http code 202
---
- Closed: #385
=> [GWL-385] fix: 닉네임 중복시http code 202

iOS/Projects/Features/SignUp/Sources/Presentation/SignUpProfileScene/SignUpProfileViewController.swift
|결과|
|:-:|
|<img src="https://github.com/JongPyoAhn/Python/assets/68585628/74cbfede-c07b-414e-9c50-d490e555e75b">|
<br/><br/>
❌
<br/><br/>
❌
<br/><br/>
---
- Closed: #392
=> [GWL-392] 카메라로 사진올릴 때, 다운샘플링 안되는 현상 픽스

.github/workflows/iOS_CI.yml, iOS/Projects/App/WeTri/Sources/CommonScene/Coordinator/AppCoordinator.swift, iOS/Projects/Features/Home/Sources/Presntaion/HomeScene/ViewController/HomeViewController.swift, iOS/Projects/Features/Record/Sources/Domain/Entities/KalmanFilterUpdateRequireElement.swift, iOS/Projects/Features/Record/Sources/Domain/UseCases/KalmanFilter.swift, iOS/Projects/Features/Record/Sources/Domain/UseCases/KalmanUseCase.swift, iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/RouteMapScene/WorkoutRouteMapViewController.swift, iOS/Projects/Features/Record/Sources/Presentation/WorkoutSessionGroupScene/RouteMapScene/WorkoutRouteMapViewModel.swift, iOS/Projects/Shared/DesignSystem/Sources/GWPageConrol.swift
N/A
<br/><br/>
- simd를 활용하여 kalmanfilter수식을 계산
<br/><br/>
- 기존 `let locations: [CLLocation]` 이 아닌 `let location: [CLLocationCoordinate2D]` 로 변경
<br/><br/>
<br/><br/>
---
- Closed: #424
=> [GWL-424] 칼만필터 발열 이슈 버그 수정
